-- MySQL Script generated by MySQL Workbench
-- Thu Jun  6 21:07:43 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Species`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Species` (
  `Species ID` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Species ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Breed`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Breed` (
  `Breed ID` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(70) NOT NULL,
  `Species_Species ID` INT NOT NULL,
  PRIMARY KEY (`Breed ID`, `Species_Species ID`),
  INDEX `fk_Breed_Species_idx` (`Species_Species ID` ASC),
  CONSTRAINT `fk_Breed_Species`
    FOREIGN KEY (`Species_Species ID`)
    REFERENCES `mydb`.`Species` (`Species ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pet`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Pet` (
  `Pet ID` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NOT NULL,
  `Gender` ENUM('Male', 'Female') NOT NULL,
  `Date of Birth` DATE NOT NULL,
  `Age` DOUBLE,
  `Breed_Breed ID` INT NOT NULL,
  `Breed_Species_Species ID` INT NOT NULL,
  PRIMARY KEY (`Pet ID`),
  INDEX `fk_Pet_Breed1_idx` (`Breed_Breed ID` ASC, `Breed_Species_Species ID` ASC),
  CONSTRAINT `fk_Pet_Breed1`
    FOREIGN KEY (`Breed_Breed ID` , `Breed_Species_Species ID`)
    REFERENCES `mydb`.`Breed` (`Breed ID` , `Species_Species ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`User` (
  `CNIC` VARCHAR(20) NOT NULL,
  `First Name` VARCHAR(45) NOT NULL,
  `Middle Name` VARCHAR(45) NULL,
  `Last Name` VARCHAR(45) NOT NULL,
  `Address` VARCHAR(50) NOT NULL,
  `Phone Number` VARCHAR(20) NOT NULL,
  `Email` VARCHAR(45) NOT NULL,
  `Password` VARCHAR(8) NOT NULL,
  `Name` VARCHAR(45),
  PRIMARY KEY (`CNIC`),
  UNIQUE INDEX `Password_UNIQUE` (`Password` ASC) ,
  UNIQUE INDEX `Email_UNIQUE` (`Email` ASC)`enrolled case`employee)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Employee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Employee` (
  `Employee ID` INT NOT NULL AUTO_INCREMENT,
  `Education` VARCHAR(45) NOT NULL,
  `Qualification` VARCHAR(45) NOT NULL,
  `Hire Date` DATE NOT NULL,
  `Working Hours` INT NOT NULL,
  `User_CNIC` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`Employee ID`),
  INDEX `fk_Employee_User1_idx` (`User_CNIC` ASC),
  CONSTRAINT `fk_Employee_User1`
    FOREIGN KEY (`User_CNIC`)
    REFERENCES `mydb`.`User` (`CNIC`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Department`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Department` (
  `Department ID` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NULL,
  `Address` VARCHAR(45) NOT NULL,
  `Phone Number` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Department ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Manager`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Manager` (
  `Employee ID` INT NOT NULL AUTO_INCREMENT,
  `Managing Years` INT NOT NULL,
  `Salary` DECIMAL(8,2) NOT NULL,
  `Education` VARCHAR(45) NOT NULL,
  `Qualification` VARCHAR(45) NOT NULL,
  `User_CNIC` VARCHAR(20) NOT NULL,
  `Department_Department ID` INT NOT NULL,
  PRIMARY KEY (`Employee ID`),
  INDEX `fk_Manager_User1_idx` (`User_CNIC` ASC) ,
  INDEX `fk_Manager_Department1_idx` (`Department_Department ID` ASC) ,
  CONSTRAINT `fk_Manager_User1`
    FOREIGN KEY (`User_CNIC`)
    REFERENCES `mydb`.`User` (`CNIC`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Manager_Department1`
    FOREIGN KEY (`Department_Department ID`)
    REFERENCES `mydb`.`Department` (`Department ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Service`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Service` (
  `Service ID` INT NOT NULL,
  `Service Name` VARCHAR(45) NOT NULL,
  `Cost Per Unit` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`Service ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Owner`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Owner` (
  `User_CNIC` VARCHAR(20) NOT NULL,
  INDEX `fk_Owner_User1_idx` (`User_CNIC` ASC) ,
  PRIMARY KEY (`User_CNIC`),
  CONSTRAINT `fk_Owner_User1`
    FOREIGN KEY (`User_CNIC`)
    REFERENCES `mydb`.`User` (`CNIC`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pet Owner`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Pet Owner` (
  `Pet_Pet ID` INT NOT NULL,
  `Owner_User_CNIC` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`Pet_Pet ID`, `Owner_User_CNIC`),
  INDEX `fk_Pet_has_Owner_Owner1_idx` (`Owner_User_CNIC` ASC) ,
  INDEX `fk_Pet_has_Owner_Pet1_idx` (`Pet_Pet ID` ASC) ,
  CONSTRAINT `fk_Pet_has_Owner_Pet1`
    FOREIGN KEY (`Pet_Pet ID`)
    REFERENCES `mydb`.`Pet` (`Pet ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pet_has_Owner_Owner1`
    FOREIGN KEY (`Owner_User_CNIC`)
    REFERENCES `mydb`.`Owner` (`User_CNIC`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Enrolled Case`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Enrolled Case` (
  `Case ID` INT NOT NULL AUTO_INCREMENT,
  `Admission` DATETIME(1) NOT NULL,
  `Discharge` DATETIME(1) NOT NULL,
  `Notes` LONGTEXT NULL,
  `Department_Department ID` INT NOT NULL,
  `Employee_Employee ID` INT NOT NULL,
  `Pet_Pet ID` INT NOT NULL,
  PRIMARY KEY (`Case ID`),
  INDEX `fk_Enrolled Cases_Department1_idx` (`Department_Department ID` ASC) ,
  INDEX `fk_Enrolled Cases_Employee1_idx` (`Employee_Employee ID` ASC) ,
  INDEX `fk_Enrolled Cases_Pet1_idx` (`Pet_Pet ID` ASC) ,
  CONSTRAINT `fk_Enrolled Cases_Department1`
    FOREIGN KEY (`Department_Department ID`)
    REFERENCES `mydb`.`Department` (`Department ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Enrolled Cases_Employee1`
    FOREIGN KEY (`Employee_Employee ID`)
    REFERENCES `mydb`.`Employee` (`Employee ID`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Enrolled Cases_Pet1`
    FOREIGN KEY (`Pet_Pet ID`)
    REFERENCES `mydb`.`Pet` (`Pet ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Status Type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Status Type` (
  `Type ID` INT NOT NULL,
  `Type` ENUM('Physical', 'Social', 'Behavioral', 'Appetite', 'General') NULL,
  PRIMARY KEY (`Type ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Current Status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Current Status` (
  `Status ID` INT NOT NULL AUTO_INCREMENT,
  `Status` VARCHAR(45) NOT NULL,
  `Status Type_Type ID` INT NOT NULL,
  PRIMARY KEY (`Status ID`, `Status Type_Type ID`),
  INDEX `fk_Current Status_Status Type1_idx` (`Status Type_Type ID` ASC) ,
  CONSTRAINT `fk_Current Status_Status Type1`
    FOREIGN KEY (`Status Type_Type ID`)
    REFERENCES `mydb`.`Status Type` (`Type ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Case Status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Case Status` (
  `Enrolled Cases_Case ID` INT NOT NULL,
  `Current Status_Status ID` INT NOT NULL,
  `Current Status_Status Type_Type ID` INT NOT NULL,
  `Checked Time` DATETIME(2) NOT NULL,
  PRIMARY KEY (`Enrolled Cases_Case ID`, `Current Status_Status ID`, `Current Status_Status Type_Type ID`),
  INDEX `fk_Enrolled Cases_has_Current Status_Current Status1_idx` (`Current Status_Status ID` ASC, `Current Status_Status Type_Type ID` ASC) ,
  INDEX `fk_Enrolled Cases_has_Current Status_Enrolled Cases1_idx` (`Enrolled Cases_Case ID` ASC) ,
  CONSTRAINT `fk_Enrolled Cases_has_Current Status_Enrolled Cases1`
    FOREIGN KEY (`Enrolled Cases_Case ID`)
    REFERENCES `mydb`.`Enrolled Case` (`Case ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Enrolled Cases_has_Current Status_Current Status1`
    FOREIGN KEY (`Current Status_Status ID` , `Current Status_Status Type_Type ID`)
    REFERENCES `mydb`.`Current Status` (`Status ID` , `Status Type_Type ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Service Provided`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Service Provided` (
  `Service_Service ID` INT NOT NULL,
  `Enrolled Case_Case ID` INT NOT NULL,
  `Start Time` DATETIME NOT NULL,
  `End Time` DATETIME NOT NULL,
  PRIMARY KEY (`Service_Service ID`, `Enrolled Case_Case ID`),
  INDEX `fk_Service_has_Enrolled Case_Enrolled Case1_idx` (`Enrolled Case_Case ID` ASC) ,
  INDEX `fk_Service_has_Enrolled Case_Service1_idx` (`Service_Service ID` ASC) ,
  CONSTRAINT `fk_Service_has_Enrolled Case_Service1`
    FOREIGN KEY (`Service_Service ID`)
    REFERENCES `mydb`.`Service` (`Service ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Service_has_Enrolled Case_Enrolled Case1`
    FOREIGN KEY (`Enrolled Case_Case ID`)
    REFERENCES `mydb`.`Enrolled Case` (`Case ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Department for Service`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Department for Service` (
  `Service_Service ID` INT NOT NULL,
  `Department_Department ID` INT NOT NULL,
  `Capacity` INT NULL,
  PRIMARY KEY (`Service_Service ID`, `Department_Department ID`),
  INDEX `fk_Service_has_Department_Department1_idx` (`Department_Department ID` ASC) ,
  INDEX `fk_Service_has_Department_Service1_idx` (`Service_Service ID` ASC) ,
  CONSTRAINT `fk_Service_has_Department_Service1`
    FOREIGN KEY (`Service_Service ID`)
    REFERENCES `mydb`.`Service` (`Service ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Service_has_Department_Department1`
    FOREIGN KEY (`Department_Department ID`)
    REFERENCES `mydb`.`Department` (`Department ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Bill`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Bill` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Time Stamp` DATETIME(1) NULL,
  `Amount` INT,
  `Paid` TINYINT NULL,
  `Enrolled Case_Case ID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_Bill_Enrolled Case1_idx` (`Enrolled Case_Case ID` ASC) ,
  CONSTRAINT `fk_Bill_Enrolled Case1`
    FOREIGN KEY (`Enrolled Case_Case ID`)
    REFERENCES `mydb`.`Enrolled Case` (`Case ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
